[0m09:21:13.902620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6B177D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6B0A3320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6B19AF00>]}


============================== 09:21:13.919667 | 63e6233c-fccf-4c73-94fc-3ed54b159412 ==============================
[0m09:21:13.919667 [info ] [MainThread]: Running with dbt=1.7.18
[0m09:21:13.919667 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\User\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:21:13.919667 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\User\Desktop\nes_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:21:13.919667 [debug] [MainThread]: Command `dbt docs generate` failed at 09:21:13.919667 after 0.13 seconds
[0m09:21:13.919667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F66A2F4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6B1CD2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019F6B1CF980>]}
[0m09:21:13.932543 [debug] [MainThread]: Flushing usage events
[0m17:33:48.764937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CF4967E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CF495190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CF4965A0>]}


============================== 17:33:48.771540 | ddb31da9-aed0-482e-8919-7d5e883d86e0 ==============================
[0m17:33:48.771540 [info ] [MainThread]: Running with dbt=1.7.10
[0m17:33:48.772998 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\User\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run -s 3+ dm_ser_per_source', 'send_anonymous_usage_stats': 'True'}
[0m17:33:48.773526 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\User\Desktop\nes_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:33:48.775583 [debug] [MainThread]: Command `dbt run` failed at 17:33:48.775583 after 0.13 seconds
[0m17:33:48.775583 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CF11E540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CEB5C3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6CF495430>]}
[0m17:33:48.775583 [debug] [MainThread]: Flushing usage events
